#!/bin/sh
################################################################################
# Copyright (c) 2025 ModalAI, Inc. All rights reserved.
#
# author: james@modalai.com
################################################################################

# try to reload services, but don't fail if it can't
set +e
if [ -f /bin/systemctl ]; then
	systemctl daemon-reload
fi

# exit 0 even if systemctl failed
exit 0
